# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Development BLOG
description: > # this means to ignore newlines until "baseurl:"
  Soo Young's first blog
repository: https://github.com/wemake-services/jekyll-theme-hackcss
baseurl: /blog  # the subpath of your site, e.g. /blog
url: https://soo-young-kim.github.io  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: markdown  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: Soo Young Kim
email: john555578@gmail.com

navigation:
  - text: Home
    url: /
  - text: Docs
    url: /docs
  - text: Coding Manual
    url: /examples

social:
  - service: github
    username: soo-young-kim
    link: https://github.com/soo-young-kim/blog

# Plugins
gems:
  - jekyll-seo-tag
